// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD07JGHr4f_snpRafwr9KCbBBaMYS725vI',
    appId: '1:785255978295:web:d3d46e15a35b1f23e436b2',
    messagingSenderId: '785255978295',
    projectId: 'authsanber-bec21',
    authDomain: 'authsanber-bec21.firebaseapp.com',
    storageBucket: 'authsanber-bec21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsC0cPpMbX-IgZGzKDApsO6CsVmUq-RBA',
    appId: '1:785255978295:android:29cdb6f0fd216648e436b2',
    messagingSenderId: '785255978295',
    projectId: 'authsanber-bec21',
    storageBucket: 'authsanber-bec21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCud_vBLLsLM6UtXH7jIKY6cmr9cAl0LMQ',
    appId: '1:785255978295:ios:4f5be9cc93b01a99e436b2',
    messagingSenderId: '785255978295',
    projectId: 'authsanber-bec21',
    storageBucket: 'authsanber-bec21.appspot.com',
    iosBundleId: 'com.example.sanberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCud_vBLLsLM6UtXH7jIKY6cmr9cAl0LMQ',
    appId: '1:785255978295:ios:182ac5df0704e209e436b2',
    messagingSenderId: '785255978295',
    projectId: 'authsanber-bec21',
    storageBucket: 'authsanber-bec21.appspot.com',
    iosBundleId: 'com.example.sanberapp.RunnerTests',
  );
}
